### PR TITLE
Validating MFMC file format

### PR DESCRIPTION
**Pull request by Vassil17**
Added function to convert laser-obtained data into MFMC (fn_laser_convert.m).
Added DataReviewer.m to plot MFMC data as cascaded A-Scans, plot 3D images of probes and wedges and compare two different MFMC files.
Changed fn_ds_convert.m to look from which column to extract the attribute value in the config files.
Combined FIToolbox to BRAIN and BRAIN to MFMC converter into one converter (ALL_IN_ONE_CONVERTER.m).
Added test data folder to run the functions with.

[Validating MFMC report.pdf](https://github.com/UoS-EEE-Automation/mfmc/files/5276740/Validating.MFMC.report.pdf)

### CODE REVIEW

**Comment by Vassil17** [comment]
Haven't checked how much memory MATLAB was using for the conversion from the raw data files to MFMC

**Comment by SuborbitalPigeon** [comment]
Just a wee comment, the main reason I created this fork of the Bristol repository was so I could do some work on a python package for doing stuff with MFMC files.

**Comment by SuborbitalPigeon** [comment]
I've decided to move that stuff to its own repository, `pymfmc`.

**Comment by DaveLines** [comment]
Hi Bruce,
The MFMC validation was all Matlab done by the summer interns but pymfmc states that it's python code. Is there any reason why you moved it?
Dave

David Lines
Knowledge Exchange Fellow
Centre for Ultrasonic Engineering (CUE)
Department of Electronic & Electrical Engineering
University of Strathclyde
Technology & Innovation Centre - Level 7
99 George Street
Glasgow G1 1RD
(Monday-Thursday inclusive)

Tel:   +44 (0) 141 444 7404
david.lines@strath.ac.uk<mailto:david.lines@strath.ac.uk>
________________________________

**Comment by SuborbitalPigeon** [comment]
> Hi Bruce, The MFMC validation was all Matlab done by the summer interns but pymfmc states that it's python code. Is there any reason why you moved it? Dave

I only moved my own stuff, nothing to do with the validation. I've done something rather silly here, and the request closed itself. I'll get it fixed.

**Comment by DaveLines** [comment]
Cheers
Dave

David Lines
Knowledge Exchange Fellow
Centre for Ultrasonic Engineering (CUE)
Department of Electronic & Electrical Engineering
University of Strathclyde
Technology & Innovation Centre - Level 7
99 George Street
Glasgow G1 1RD
(Monday-Thursday inclusive)

Tel:   +44 (0) 141 444 7404
david.lines@strath.ac.uk<mailto:david.lines@strath.ac.uk>
________________________________

**Comment by will-jj** [comment]
This work in this pull request is now found at:

https://github.com/UoS-EEE-Automation/mfmc-validation
https://github.com/UoS-EEE-Automation/mfmc-matlab/tree/master/Matlab/interfaces

I am locking the conversation here now.

**Pull request closed without merging**
